# Generated by Django 4.2.13 on 2026-01-08 12:22

from django.db import migrations, models
import members.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_person_photo_video_consent_external_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiprequest',
            old_name='seen',
            new_name='processed',
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='photo_video_consent_external',
            field=models.BooleanField(default=None, help_text='Can we use group photos and videos containing you for external purposes (website, social media and other promotional activities)?', null=True, verbose_name='External non-group'),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='photo_video_consent_external_group',
            field=models.BooleanField(default=None, help_text='Can we use other photos and videos containing you for external purposes (website, social media and other promotional activities)?', null=True, verbose_name='External group'),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='photo_video_consent_internal',
            field=models.BooleanField(default=None, help_text='Can we share photos and videos containing you internally with other members of Quadrivium?', null=True, verbose_name='Internal'),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='sub_association',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vokollage', 'Vokollage – choir'), ('ensuite', 'Ensuite – symphony orchestra'), ('auletes', 'Auletes – wind orchestra'), ('piano', 'Piano member – join association-wide activities and use our rehearsal rooms')], help_text='Which sub-associations are you interested in? If you are not interested in the orchestra and choir, select piano member. Leave empty if you are not (yet) sure.', max_length=200, verbose_name='sub-association'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='initials',
            field=models.CharField(blank=True, help_text='Initials of your first name(s), so excluding your surname(s). For example: Anna Maria Janssen gives A.M.', max_length=30),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='is_student',
            field=models.BooleanField(blank=True, help_text='If you’re a student at any school or university, indicate yes.', null=True, verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='tue_card_number',
            field=models.IntegerField(blank=True, help_text='If you have a TU/e campus card, fill in the number that is printed sideways, which is different from your student number or s-number. We will then make it possible for you to enter the cultural section in Luna using your campus card, during off-hours. During the day however the entrance is usually always open to anyone.', null=True, verbose_name='TU/e campus card number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Lowercase letters and numbers only.', max_length=150, unique=True, validators=[members.models.UsernameValidator()]),
        ),
    ]
