# Generated by Django 4.2.13 on 2025-10-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_rename_seen_membershiprequest_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiprequest',
            name='initials',
            field=models.CharField(blank=True, help_text='Initials of your first name(s), so excluding your surname(s). For example: Anna Maria Janssen gives A.M.', max_length=30),
        ),
    ]
